services:
    redis:
        image: redis:7-alpine
        restart: on-failure
        command: redis-server --maxmemory-policy allkeys-lru --maxmemory 200mb
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping"]
            interval: 5s
            timeout: 5s
        ports:
            - 6379:6379
